<a href="https://colab.research.google.com/github/ralsouza/data_manipulation_with_python/blob/master/notebooks/01_numpy_numerical_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To remember: Everthing in Python is an object, with methods and attributes.

Method: Make an action on object
Attribute: Characterist of object

Examples:

`# Method`

 `array2.max()`

`# Attribute`

`arra2.ndim`


In [0]:
# Import Numpy
import numpy as np

# 1. Making Data Structures with Numpy

In [0]:
# Array one-dimensional
arr1 = np.array([10,20,30,40])

In [0]:
# Array two-dimensional
arr2 = np.array([[100,200,300],[20,30,40]])

In [5]:
arr1

array([10, 20, 30, 40])

In [8]:
arr2

array([[100, 200, 300],
       [ 20,  30,  40]])

In [11]:
# Check the shape of arr1
arr1.shape

(4,)

In [12]:
# Check the shape of arr2
arr2.shape

(2, 3)

In [14]:
# Check de number of dimensions
arr2.ndim

2

In [15]:
arr1.ndim

1

## 1.2 Making Data Structures with `.arange()` function

In [17]:
# Call .arange() function indicating the number of elements needed
arr3 = np.arange(15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])