<a href="https://colab.research.google.com/github/ralsouza/data_manipulation_with_python/blob/master/notebooks/01_numpy_numerical_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To remember: Everthing in Python is an object, with methods and attributes.

Method: Make an action on object
Attribute: Characterist of object

Examples:

`# Method`

 `array2.max()`

`# Attribute`

`arra2.ndim`


In [0]:
# Import Numpy
import numpy as np

# 1. Making Data Structures with Numpy

In [0]:
# Array one-dimensional
arr1 = np.array([10,20,30,40])

In [0]:
# Array two-dimensional
arr2 = np.array([[100,200,300],[20,30,40]])

In [5]:
arr1

array([10, 20, 30, 40])

In [8]:
arr2

array([[100, 200, 300],
       [ 20,  30,  40]])

In [11]:
# Check the shape of arr1
arr1.shape

(4,)

In [12]:
# Check the shape of arr2
arr2.shape

(2, 3)

In [14]:
# Check de number of dimensions
arr2.ndim

2

In [15]:
arr1.ndim

1

## 1.1 Making Data Structures with `.arange()` function

In [19]:
# Call .arange() function indicating the number of elements needed
arr3 = np.arange(15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# Using start/end (exclusive)
arr4 = np.arange(0,15,5)
arr4

array([ 0,  5, 10])

## 1.2 Making Data Structures with `.linspace()`

In [21]:
arr5 = np.linspace(0,3,4); arr5

array([0., 1., 2., 3.])

## 1.3 Others functions to Make Data Structures

In [22]:
# Making an array filled with zeros
arr6 = np.zeros((10,8)); arr6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
# Array 2x3x2
arr7 = np.ones((2,3,2)); arr7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
# Making a Identity Matrix
arr8 = np.eye(3); arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Making the same, but specifying the numbers
arr9 = np.diag((2,1,4,6)); arr9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [26]:
# numpy.random.rand
# This function produces a sequence of numbers evenly distributed between 0 and n
arr10 = np.random.rand(5); arr10

array([0.1553103 , 0.11370327, 0.89100967, 0.64391248, 0.50451947])

In [29]:
# numpy.random.randn
# This function produces a sequence of numbers with normal distribuition (Gaussian)
arr11 = np.random.randn(5); arr11

array([ 0.18500141, -1.04919057,  1.46073875, -0.49842971,  1.42895111])

In [33]:
# Making a empty matrix
arr13 = np.empty((3,2)); arr13

array([[4.94e-322, 9.88e-322],
       [1.48e-321, 9.88e-323],
       [1.48e-322, 1.98e-322]])

In [36]:
# Function .tile() to replicate a structure
# First take some array
arr14 = np.array([[9,4],[3,7]]); arr14

array([[9, 4],
       [3, 7]])

In [37]:
# To tile arr14, 4 times by row
np.tile(arr14,4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [38]:
# To tile arr14, 4 times by row and column
np.tile(arr14,(2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

# 2. Data Types

In [39]:
# Making an array with float numbers
arr15 = np.array([8,-3,5,9],dtype='float'); arr15

array([ 8., -3.,  5.,  9.])

In [40]:
# Check data type
arr15.dtype

dtype('float64')

In [42]:
# By default, arrays are maked with integer
arr16 = np.array([2,4,6,8]); arr16

array([2, 4, 6, 8])

In [43]:
arr16.dtype

dtype('int64')

In [44]:
# Making a array with one number as float
arr17 = np.array([2.4,5,2,6]); arr17

array([2.4, 5. , 2. , 6. ])

In [45]:
arr17.dtype

dtype('float64')

In [47]:
# Making an array with strings
arr18 = np.array(['Data','Analysis','with Python']); arr18.dtype

dtype('<U11')

In [48]:
# Making an array with boolean values
arr19 = np.array([True,False,False]); arr19.dtype

dtype('bool')

In [49]:
# Try to convert an array from float64 to int64
# the float numbers are rounded
arr20 = np.array([7,3,-4.5]); arr20.astype(int)

array([ 7,  3, -4])

# 3. Making Operations with Matrices

In [52]:
# Multiply by 5
arr21 = np.arange(0,30) * 5; arr21

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [53]:
# Elevate to power 4
arr22 = np.arange(0,30) ** 4; arr22

array([     0,      1,     16,     81,    256,    625,   1296,   2401,
         4096,   6561,  10000,  14641,  20736,  28561,  38416,  50625,
        65536,  83521, 104976, 130321, 160000, 194481, 234256, 279841,
       331776, 390625, 456976, 531441, 614656, 707281])

In [54]:
# Add 1 to each element of array
arr23 = np.arange(0,30) + 1; arr23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [0]:
# Operation between arrays
# Making two arrays
arr24 = np.arange(0,30,3) + 3
arr25 = np.arange(1,11)

In [56]:
# Subtract
arr24 - arr25

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [57]:
# Add
arr24 + arr25

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [58]:
# Multiply
arr24 * arr25

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [59]:
# Divide
arr24 / arr25

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [60]:
# Comparing values between arrays
arr24 > arr25

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [63]:
# Making logical tests
arrA = np.array([True,False,True,False])
arrB = np.array([False,False,True,False])

np.logical_and(arrA,arrB)

array([False, False,  True, False])