<a href="https://colab.research.google.com/github/ralsouza/data_manipulation_with_python/blob/master/notebooks/01_numpy_numerical_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To remember: Everthing in Python is an object, with methods and attributes.

Method: Make an action on object
Attribute: Characterist of object

Examples:

`# Method`

 `array2.max()`

`# Attribute`

`arra2.ndim`


In [0]:
# Import Numpy
import numpy as np

# 1. Making Data Structures with Numpy

In [0]:
# Array one-dimensional
arr1 = np.array([10,20,30,40])

In [0]:
# Array two-dimensional
arr2 = np.array([[100,200,300],[20,30,40]])

In [5]:
arr1

array([10, 20, 30, 40])

In [8]:
arr2

array([[100, 200, 300],
       [ 20,  30,  40]])

In [11]:
# Check the shape of arr1
arr1.shape

(4,)

In [12]:
# Check the shape of arr2
arr2.shape

(2, 3)

In [14]:
# Check de number of dimensions
arr2.ndim

2

In [15]:
arr1.ndim

1

## 1.1 Making Data Structures with `.arange()` function

In [19]:
# Call .arange() function indicating the number of elements needed
arr3 = np.arange(15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
# Using start/end (exclusive)
arr4 = np.arange(0,15,5)
arr4

array([ 0,  5, 10])

## 1.2 Making Data Structures with `.linspace()`

In [21]:
arr5 = np.linspace(0,3,4); arr5

array([0., 1., 2., 3.])

## 1.3 Others functions to Make Data Structures

In [22]:
# Making an array filled with zeros
arr6 = np.zeros((10,8)); arr6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
# Array 2x3x2
arr7 = np.ones((2,3,2)); arr7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [24]:
# Making a Identity Matrix
arr8 = np.eye(3); arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Making the same, but specifying the numbers
arr9 = np.diag((2,1,4,6)); arr9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [26]:
# numpy.random.rand
# This function produces a sequence of numbers evenly distributed between 0 and n
arr10 = np.random.rand(5); arr10

array([0.1553103 , 0.11370327, 0.89100967, 0.64391248, 0.50451947])

In [29]:
# numpy.random.randn
# This function produces a sequence of numbers with normal distribuition (Gaussian)
arr11 = np.random.randn(5); arr11

array([ 0.18500141, -1.04919057,  1.46073875, -0.49842971,  1.42895111])

In [33]:
# Making a empty matrix
arr13 = np.empty((3,2)); arr13

array([[4.94e-322, 9.88e-322],
       [1.48e-321, 9.88e-323],
       [1.48e-322, 1.98e-322]])

In [36]:
# Function .tile() to replicate a structure
# First take some array
arr14 = np.array([[9,4],[3,7]]); arr14

array([[9, 4],
       [3, 7]])

In [37]:
# To tile arr14, 4 times by row
np.tile(arr14,4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [38]:
# To tile arr14, 4 times by row and column
np.tile(arr14,(2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])