<a href="https://colab.research.google.com/github/ralsouza/data_manipulation_with_python/blob/master/notebooks/02_numpy_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An illustration of indexing on a 2D array


![An illustration of indexing on a 2D array.](https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172112.png)




# Two-dimensional array slicing


![Two-dimensional array slicing](https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages2172114.png)

In [0]:
# Import Numpy
import numpy as np

In [6]:
arr1 = np.arange(5); arr1

array([0, 1, 2, 3, 4])

In [7]:
# First element starts by 0
arr1[0]

0

In [8]:
# Access the last item of array
arr1[-1]

4

In [14]:
# Inverting an array
arr1[::-1]

array([4, 3, 2, 1, 0])

In [15]:
# Making a three-dimensional array
arr2 = np.array([[190,290,490],[129,458,567],[761,902,346]]); arr2

array([[190, 290, 490],
       [129, 458, 567],
       [761, 902, 346]])

In [16]:
# Slicing [2,1] position
arr2[2,1]

902

In [17]:
# Assigning a value in an array
arr2[1,1] = 10; arr2

array([[190, 290, 490],
       [129,  10, 567],
       [761, 902, 346]])

In [18]:
# Return one element from matrix
arr2[2]

array([761, 902, 346])

In [20]:
# It's the same (best practice)
arr2[2,]

array([761, 902, 346])

In [27]:
# Return the second column
arr2[:,1]

array([290,  10, 902])

In [35]:
# Return a value from an index that doesn't exist
# Will return the error: index x is out of bounds for axis x with size x
arr2[5]

IndexError: ignored

In [38]:
# Making a array one-dimensional
arr3 = np.arange(50) * 2; arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [39]:
# Return the values from 5 to 10 (exclusive) position, skipping 2 positions
arr3[5:10:2]

array([10, 14, 18])

In [40]:
# Return the values up to the index 4 (exclusive)
arr3[:4]

array([0, 2, 4, 6])

In [41]:
# Return the values from index 4
arr3[4:]

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40,
       42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74,
       76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
# Replace the values up to first three positions
arr3[:3] = 1; arr3

array([ 1,  1,  1,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [51]:
# Reset arr3
arr3 = np.arange(50) * 2; arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [52]:
# Assigning an array to another array
arr3[:4] = np.ones(4); arr3

array([ 1,  1,  1,  1,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Making a subsetting of an array

In [54]:
arr4 = np.arange(12); arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
# Subsetting steping by 1
arr5 = arr4[::2]; arr5

array([ 0,  2,  4,  6,  8, 10])

array([ 0,  2,  4,  6,  8, 10])

# Making a copy of object

In [60]:
arr6 = np.arange(10); arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr7 = arr6.copy(); arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])