<a href="https://colab.research.google.com/github/ralsouza/data_manipulation_with_python/blob/master/notebooks/03_numpy_transpose_reshaping_of_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [4]:
arr1 = np.array([[65,23,19],[41,87,10]]); arr1

array([[65, 23, 19],
       [41, 87, 10]])

In [5]:
# Transpose (pivot) the matriz
arr1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [6]:
# Same result
np.transpose(arr1)

array([[65, 41],
       [23, 87],
       [19, 10]])

# Broadcasting

In [8]:
arr2 = np.array([[34,35,36]]); arr2

array([[34, 35, 36]])

In [9]:
arr2.T

array([[34],
       [35],
       [36]])

In [10]:
arr2.T + arr2

array([[68, 69, 70],
       [69, 70, 71],
       [70, 71, 72]])

# Transforming Matrices in Vectors

In [11]:
# Make a matrix multidimensional  
arr3 = np.array([np.arange(1,6),np.arange(10,15)]); arr3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [12]:
# Transform to one-dimensional
arr3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [13]:
arr3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

# Logical Operators

In [0]:
np.random.seed(100)

In [15]:
arr4 = np.random.randint(1,10,size=(4,4)); arr4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [16]:
# Check if "any" value is divisible by 7. If any is, return True
np.any((arr4 % 7) == 0)

False

In [17]:
# Check if all elements are less than 11
np.all(arr4 <11)

True

# Reshaping

In [19]:
arr5 = np.arange(1,16); arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
# Reshaping array to multidimensional shape
arr5.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Sorting an Array

In [21]:
arr6 = np.array([[3,2],[10,-1]]); arr6

array([[ 3,  2],
       [10, -1]])

In [23]:
# Sorting by row
arr6.sort(axis=1); arr6

array([[ 2,  3],
       [-1, 10]])

In [24]:
# Sort by column
arr6.sort(axis=0); arr6

array([[-1,  3],
       [ 2, 10]])